@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createcommutenetwork.content.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;